# Generated by Django 4.1 on 2022-08-11 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('subdepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdepartment_user', to='core.subdepartment')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sub_subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_subdepartment_user', to='core.sub_subdepartment'),
        ),
    ]
