# Generated by Django 4.1 on 2022-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='kpi_q1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kpi_q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kpi_q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='kpi_q4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
